from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from utils import DISCLAIMER_TEXT, write_json


SUMMARY_DISCLAIMER = (
    "Provisional differential generated by research AI system. "
    "Not a diagnosis. Requires clinician review."
)


SECTION_LABELS = {
    "history_of_presenting_illness": "AI-collected HPI",
    "personal_history": "Personal history",
    "past_treatment_history": "Past/treatment history",
    "family_history": "Family history",
}


def normalize_answer(value: Any) -> str:
    if value is None or value == "":
        return "Not recorded"
    if isinstance(value, bool):
        return "Yes" if value else "No"
    return str(value)


def format_structured_hpi(patient_intake: dict[str, Any], answers: dict[str, Any]) -> str:
    body_part = patient_intake.get("body_part_affected") or "unspecified site"
    complaint = patient_intake.get("chief_complaint") or "skin lesion"
    duration = answers.get("lesion_duration") or answers.get("duration") or "duration not recorded"
    progression = answers.get("lesion_progression") or answers.get("progression") or "progression not recorded"

    symptom_parts: list[str] = []
    for answer_id, positive_text, negative_text in [
        ("itching", "itching", "no itching"),
        ("pain", "pain", "no pain"),
        ("fever", "fever", "no fever"),
        ("pus_or_discharge", "pus or discharge", "no pus or discharge"),
        ("bleeding_or_ulceration", "bleeding or ulceration", "no bleeding or ulceration"),
    ]:
        value = answers.get(answer_id)
        if isinstance(value, bool):
            symptom_parts.append(positive_text if value else negative_text)

    morphology_parts: list[str] = []
    for answer_id, text in [
        ("ring_shaped", "ring-shaped"),
        ("central_clearing", "with central clearing"),
        ("scaling_at_border", "with scaling at the border"),
        ("asymmetry", "asymmetrical"),
        ("irregular_border", "with irregular borders"),
        ("multiple_colors_dark_areas", "with color variation or dark areas"),
        ("white_hair_over_patch", "with white hair over the patch"),
    ]:
        if answers.get(answer_id) is True:
            morphology_parts.append(text)

    lines = [
        f"Patient presents with {complaint} over the {body_part}.",
        f"The lesion has been present for {duration} and is described as {progression}.",
    ]
    if symptom_parts:
        lines.append(f"Associated symptoms: {', '.join(symptom_parts)}.")
    if morphology_parts:
        lines.append(f"Reported lesion features: {', '.join(morphology_parts)}.")
    return " ".join(lines)


def build_answer_sections(answers: dict[str, Any], questions: list[dict[str, Any]]) -> dict[str, dict[str, str]]:
    sections = {key: {} for key in SECTION_LABELS}
    question_lookup = {question["id"]: question for question in questions}

    for answer_id, value in answers.items():
        question = question_lookup.get(answer_id)
        section = question.get("section") if question else None
        if section not in sections:
            continue
        label = question.get("text", answer_id) if question else answer_id
        sections[section][label] = normalize_answer(value)
    return sections


def format_predictions(predictions_payload: dict[str, Any] | list[dict[str, Any]]) -> list[dict[str, Any]]:
    if isinstance(predictions_payload, dict) and isinstance(predictions_payload.get("branches"), dict):
        combined_rows: list[dict[str, Any]] = []
        for branch_name, branch_payload in predictions_payload["branches"].items():
            for row in branch_payload.get("top_predictions", []):
                combined_rows.append(
                    {
                        "label": f"{branch_name}: {row.get('label', '')}",
                        "probability": round(float(row.get("probability", row.get("prob", 0.0))), 6),
                    }
                )
        return combined_rows

    rows = (
        predictions_payload.get("top_predictions", predictions_payload)
        if isinstance(predictions_payload, dict)
        else predictions_payload
    )
    formatted = []
    for row in rows:
        formatted.append(
            {
                "label": str(row.get("label", "")),
                "probability": round(float(row.get("probability", row.get("prob", 0.0))), 6),
            }
        )
    return formatted


def infer_model_uncertainty(predictions: list[dict[str, Any]], confidence_level: str | None) -> str:
    if confidence_level:
        normalized = confidence_level.strip().lower()
        if normalized == "high":
            return "low uncertainty"
        if normalized == "moderate":
            return "moderate uncertainty"
        if normalized == "low":
            return "high uncertainty"
        return "unknown"
    if not predictions:
        return "unknown"
    max_prob = max(item["probability"] for item in predictions)
    if max_prob >= 0.75:
        return "low uncertainty"
    if max_prob >= 0.45:
        return "moderate uncertainty"
    return "high uncertainty"


def infer_combined_confidence_level(predictions_payload: dict[str, Any] | list[dict[str, Any]]) -> str | None:
    if isinstance(predictions_payload, dict) and isinstance(predictions_payload.get("branches"), dict):
        levels = [
            str(branch_payload.get("confidence_level", "")).lower()
            for branch_payload in predictions_payload["branches"].values()
        ]
        if "high" in levels:
            return "high"
        if "moderate" in levels:
            return "moderate"
        if "low" in levels:
            return "low"
        return None
    if isinstance(predictions_payload, dict):
        return predictions_payload.get("confidence_level")
    return None


def generate_summary(
    patient_intake: dict[str, Any],
    predictions_payload: dict[str, Any] | list[dict[str, Any]],
    engine_output: dict[str, Any],
    answers: dict[str, Any],
    image_quality_warning: str | None = None,
) -> dict[str, Any]:
    predictions = format_predictions(predictions_payload)
    questions = engine_output.get("questions", [])
    scoring = engine_output.get("scoring", engine_output)
    answer_sections = build_answer_sections(answers, questions)
    confidence_level = infer_combined_confidence_level(predictions_payload)

    return {
        "patient_entered": {
            "anonymized_patient_id": patient_intake.get("patient_id") or patient_intake.get("name"),
            "name_or_id": patient_intake.get("name") or patient_intake.get("patient_id"),
            "age": patient_intake.get("age"),
            "sex": patient_intake.get("sex"),
            "address_or_region": patient_intake.get("address") or patient_intake.get("region"),
            "occupation": patient_intake.get("occupation"),
            "education": patient_intake.get("education"),
            "body_part_affected": patient_intake.get("body_part_affected"),
            "chief_complaint": patient_intake.get("chief_complaint"),
        },
        "lesion_metadata": {
            "color": patient_intake.get("lesion_color"),
            "shape": patient_intake.get("lesion_shape"),
            "border": patient_intake.get("lesion_border"),
            "size": patient_intake.get("lesion_size"),
            "pattern": patient_intake.get("lesion_pattern"),
            "pigmentation": patient_intake.get("lesion_pigmentation"),
            "surface_change": patient_intake.get("lesion_surface_change"),
            "lesion_count": patient_intake.get("lesion_count"),
        },
        "doctor_style_history": {
            "chief_complaint": patient_intake.get("chief_complaint") or "Not recorded",
            "history_of_presenting_illness": format_structured_hpi(patient_intake, answers),
        },
        "ai_collected_hpi": answer_sections["history_of_presenting_illness"],
        "personal_history": answer_sections["personal_history"],
        "past_treatment_history": answer_sections["past_treatment_history"],
        "family_history": answer_sections["family_history"],
        "image_model": {
            "top_k_predictions": predictions,
            "confidence_level": confidence_level,
            "model_uncertainty": infer_model_uncertainty(predictions, confidence_level),
            "image_quality_warning": image_quality_warning or "Not assessed",
        },
        "adaptive_reasoning": {
            "questioning_profile": scoring.get("profile_display_name"),
            "disease_groups": scoring.get("disease_groups", []),
            "melanoma_rule_score": scoring.get("melanoma_rule_score"),
            "branch_differentials": scoring.get("branch_differentials", {}),
            "key_positive_answers": scoring.get("key_positive_answers", []),
            "key_negative_answers": scoring.get("key_negative_answers", []),
            "red_flags": scoring.get("red_flags", []),
        },
        "output": {
            "provisional_differential_diagnosis": scoring.get("updated_differential", []),
            "urgency_level": scoring.get("urgency_level", "routine dermatologist review"),
            "suggested_doctor_review_priority": scoring.get(
                "doctor_review_priority", "Clinician review required."
            ),
            "disclaimer": SUMMARY_DISCLAIMER,
        },
        "safety_disclaimer": DISCLAIMER_TEXT,
    }


def summary_to_text(summary: dict[str, Any]) -> str:
    lines = [
        "Doctor-Facing OPD Summary",
        "",
        SUMMARY_DISCLAIMER,
        "",
        "Patient-entered:",
    ]
    for key, value in summary["patient_entered"].items():
        lines.append(f"- {key.replace('_', ' ').title()}: {normalize_answer(value)}")

    lines.extend(["", "Lesion metadata:"])
    lesion_metadata = summary.get("lesion_metadata", {})
    for key, value in lesion_metadata.items():
        lines.append(f"- {key.replace('_', ' ').title()}: {normalize_answer(value)}")

    lines.extend(["", "Doctor-style history:"])
    lines.append(f"- Chief complaint: {normalize_answer(summary['doctor_style_history'].get('chief_complaint'))}")
    lines.append(f"- History of presenting illness: {normalize_answer(summary['doctor_style_history'].get('history_of_presenting_illness'))}")

    for section_key, title in [
        ("ai_collected_hpi", "AI-collected HPI"),
        ("personal_history", "Personal history"),
        ("past_treatment_history", "Past/treatment history"),
        ("family_history", "Family history"),
    ]:
        lines.extend(["", f"{title}:"])
        section = summary.get(section_key, {})
        if section:
            for question, answer in section.items():
                lines.append(f"- {question}: {answer}")
        else:
            lines.append("- Not recorded")

    lines.extend(["", "Image model:"])
    model = summary["image_model"]
    for prediction in model["top_k_predictions"]:
        lines.append(f"- {prediction['label']}: {prediction['probability']:.3f}")
    lines.append(f"- Confidence level: {normalize_answer(model.get('confidence_level'))}")
    lines.append(f"- Model uncertainty: {model['model_uncertainty']}")
    lines.append(f"- Image quality warning: {model['image_quality_warning']}")

    reasoning = summary["adaptive_reasoning"]
    lines.extend(["", "Adaptive reasoning:"])
    lines.append(f"- Questioning profile: {normalize_answer(reasoning.get('questioning_profile'))}")
    disease_groups = reasoning.get("disease_groups", [])
    lines.append(f"- Disease groups considered: {', '.join(disease_groups) if disease_groups else 'Not recorded'}")
    if reasoning.get("melanoma_rule_score") is not None:
        lines.append(f"- Melanoma rule score: {normalize_answer(reasoning.get('melanoma_rule_score'))}")
    lines.append(f"- Key positive answers: {', '.join(reasoning['key_positive_answers']) or 'None recorded'}")
    lines.append(f"- Key negative answers: {', '.join(reasoning['key_negative_answers']) or 'None recorded'}")
    red_flags = [flag["text"] for flag in reasoning["red_flags"]]
    lines.append(f"- Red flags: {', '.join(red_flags) or 'None recorded'}")
    branch_differentials = reasoning.get("branch_differentials", {})
    if branch_differentials:
        for branch_name, branch_rows in branch_differentials.items():
            preview = ", ".join(
                f"{item['display_name']} ({item['score']})"
                for item in branch_rows[:3]
            )
            lines.append(f"- {branch_name} branch differential: {preview or 'None recorded'}")

    output = summary["output"]
    lines.extend(["", "Output:"])
    for item in output["provisional_differential_diagnosis"][:5]:
        lines.append(f"- {item['display_name']}: score {item['score']}")
    lines.append(f"- Urgency level: {output['urgency_level']}")
    lines.append(f"- Suggested doctor review priority: {output['suggested_doctor_review_priority']}")
    lines.append(f"- Disclaimer: {output['disclaimer']}")
    lines.append(f"- Safety disclaimer: {summary['safety_disclaimer']}")
    return "\n".join(lines)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate doctor-facing OPD summary.")
    parser.add_argument("--patient", required=True, help="JSON file or JSON string with patient intake")
    parser.add_argument("--predictions", required=True, help="JSON file or JSON string with model predictions")
    parser.add_argument("--engine_output", required=True, help="JSON file or JSON string from question_engine")
    parser.add_argument("--answers", required=True, help="JSON file or JSON string with collected answers")
    parser.add_argument("--output_json", default=None, help="Optional JSON output path")
    parser.add_argument("--output_txt", default=None, help="Optional text output path")
    parser.add_argument("--image_quality_warning", default=None)
    return parser.parse_args()


def load_json_arg(value: str) -> Any:
    path = Path(value)
    if path.exists():
        with open(path, "r", encoding="utf-8") as handle:
            return json.load(handle)
    return json.loads(value)


def main() -> None:
    args = parse_args()
    summary = generate_summary(
        patient_intake=load_json_arg(args.patient),
        predictions_payload=load_json_arg(args.predictions),
        engine_output=load_json_arg(args.engine_output),
        answers=load_json_arg(args.answers),
        image_quality_warning=args.image_quality_warning,
    )
    text = summary_to_text(summary)

    if args.output_json:
        write_json(args.output_json, summary)
    if args.output_txt:
        path = Path(args.output_txt)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")

    print(text)


if __name__ == "__main__":
    main()
